/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    FooterInfo: typeof import('./src/components/Footer/FooterInfo.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HeaderAccount: typeof import('./src/components/Header/HeaderAccount/HeaderAccount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar/SideBar.vue')['default']
  }
}
